#### ####  See https://pre-commit.com for more information
#### ####  See https://pre-commit.com/hooks.html for more hooks
exclude: '.md$'
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
                '--disable=E0401,E1101,E1102,R0913,R0914,W0703,E0602,C0103,C0114,W0611,W0102,C0330,C0326,W0107,R1716,R0902,E0611,E1124',
                '--fail-under=7.5',
                '-rn', # Only message dysplay
                '-sn', # Don't display the score
                '--rcfile=.pylintrc', # Link to your config file
                '--load-plugins=pylint.extensions.docparams', #load an extension
                ]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv\Scripts\activate;pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]

  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        description: trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

      - id: end-of-file-fixer
        name: fix end of files
        description: ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: python
        types: [text]
        stages: [commit, push, manual]

      - id: check-yaml
        name: check yaml
        description: checks yaml files for parseable syntax.
        entry: check-yaml
        language: python
        types: [yaml]
        stages: [commit]

      - id: check-added-large-files
        name: check for added large files
        description: prevents giant files from being committed.
        entry: check-added-large-files
        language: python

      - id: check-ast
        name: check python ast
        description: simply checks whether the files parse as valid python.
        entry: check-ast
        language: python
        types: [python]

      - id: check-docstring-first
        name: check docstring is first
        description: checks a common error of defining a docstring after code.
        entry: check-docstring-first
        language: python
        types: [python]

      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        require_serial: true
        language: python
        types_or: [python, pyi]
        args: ['--line-length=79', '--experimental-string-processing']

      - id: docformatter
        name: docformatter
        description: formats docstrings to follow PEP 257.
        entry: docformatter
        language: python
        types: [text]
        args: [--in-place]
        stages: [commit]
